spring:
  application:
    name: storyforge-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/storyforge
    username: storyforge
    password: ${DB_PASSWORD:yourpassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        types:
          print:
            banner: false
        jdbc:
          lob:
            non_contextual_creation: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com
      model: gpt-4-turbo-preview
      temperature: 0.7
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD:}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:your-secret-key-change-in-production}
  expiration: 86400000 # 24 hours

logging:
  level:
    com.storyforge: DEBUG
    org.springframework.ai: DEBUG